name = "wari"
compatibility_date = "2026-07-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "wari-db"
database_id = "413a32b9-7357-4569-b487-a0080bca4e36"
migrations_dir = "db/migrations"
